name: SMPEconomy
version: '1.0'
main: live.blackninja.economy.Economy
api-version: '1.21'
author: blackNinja46
website: blackninja.live

depend:
  - SMP

commands:
  auctionhouse:
    description: Auction House
    aliases: [ ah ]

permissions:
  ninjasmp.economy.cmd.auction.admin:
    description: Auction House Admin