name: SMP
version: '1.0'
main: live.blackninja.smp.Core
api-version: '1.21'
author: blackNinja46
website: blackninja.live

depend: [LuckPerms]

commands:
  home:
    description: An Command to set Homes
  tpa:
    description: An TPA Command
  smp:
    description: An Command to Setup an SMP
  spawn:
    description: An Command to teleport a Person to the Spawn
  voteban:
    description: Vote ban Command
    aliases: [ vote ]
  status:
    description: Set a Status with this Command
  hubschrauber:
    description: Random Command
  resourcepack:
    description: Mange the ResourcePack
  timeout:
    description: TimeOut Function Command
  untimeout:
    description: TimeOut Function Command
  ecsee:
    description: See the EnderChest of the Player
  ec:
    description: See your the EnderChest
  invsee:
    description: See the Inventory of the Player
  timer:
    description: Timer Command
  restart:
    description: Restart the Server
  errorwatcher:
    description: Observe all Error live
  scale:
    description: Scale Command
  info:
    description: Gives you infos about the Plugins
  # Staff Commands
  vanish:
    description: Vanish Command
  fly:
    description: Fly Command
  staffchat:
    description: Staff Chat Command
  staff:
    description: Staff Mode Command
  randomtp:
    description: Random Teleport Command
  freeze:
    description: Freeze Command
  heal:
    description: Heal Command


permissions:
  ninjasmp.*:
    children:
      ninjasmp.cmd.smp: true
      ninjasmp.template: true
      ninjasmp.team: true
      ninjasmp.voteban.admin: true
      ninjasmp.status.admin: true
      ninjasmp.cmd.openend: true
      ninjasmp.cmd.restart: true
      ninjasmp.rank.admin: true
      ninjasmp.cmd.scale: true
      ninjasmp.cmd.invsee: true
      ninjasmp.cmd.ecsee: true
      ninjasmp.cmd.ec: true
      ninjasmp.cmd.timeout: true
      ninjasmp.cmd.resourcepack: true
      ninjasmp.cmd.timer: true
  ninjasmp.staff.*:
    description: All Staff Permissions
    children:
      ninjasmp.staff.bypass: true
      ninjasmp.staff.cmd.vanish: true
      ninjasmp.staff.cmd.fly: true
      ninjasmp.staff.cmd.chat: true
      ninjasmp.staff.cmd.randomtp: true
      ninjasmp.staff.cmd.staffmode: true
      ninjasmp.staff.cmd.heal: true
      ninjasmp.staff.cmd.freeze: true


  ninjasmp.rank.player:
    description: Player Rank
  ninjasmp.rank.ninja+:
    description: Ninja+ Rank
  ninjasmp.rank.vip:
    description: VIP Rank
  ninjasmp.rank.moderator:
    description: Moderator Rank